M48
; DRILL file {KiCad (7.0.0)} date Thu Apr 20 18:01:28 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-20T18:01:28-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X3.2707Y-3.1378
X3.2707Y-3.311
T2
X3.2638Y-2.0827
X6.4134Y-4.1457
X6.4173Y-2.0945
T0
M30
